// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUdPsAEaL8cQuMWwWYjdJ5Nd5z7TqyTgA',
    appId: '1:131635278368:android:eb03a6f1fbb4b85715c245',
    messagingSenderId: '131635278368',
    projectId: 'iot-project-aca04',
    databaseURL: 'https://iot-project-aca04-default-rtdb.firebaseio.com',
    storageBucket: 'iot-project-aca04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYjXtWfXGlJs1LObz_CR77dfmFoHH7tag',
    appId: '1:131635278368:ios:6d94a2e4b703c4e415c245',
    messagingSenderId: '131635278368',
    projectId: 'iot-project-aca04',
    databaseURL: 'https://iot-project-aca04-default-rtdb.firebaseio.com',
    storageBucket: 'iot-project-aca04.appspot.com',
    iosBundleId: 'com.example.flutterFirebase',
  );
}
